site_name: SIA-CE Integration
site_description: Python package for automated capillary electrophoresis with Agilent ChemStation
site_author: Richard Maršala
site_url: https://github.com/yourusername/SIA-CE

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/yourusername/SIA-CE
repo_name: SIA-CE

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - ChemStation API:
      - Introduction: chemstation-api/introduction.md
      - File Protocol: chemstation-api/file-protocol.md
      - Basic Operations: chemstation-api/basic-operations.md
      - Methods & Sequences: chemstation-api/methods-sequences.md
      - Troubleshooting: chemstation-api/troubleshooting.md
  - SIA API:
      - Introduction: sia-api/introduction.md
      - Basic Operations: sia-api/basic-operations.md
      - Workflows: sia-api/workflows.md
      - Port Configuration: sia-api/port-configuration.md
  - Tutorials:
      - First Analysis: tutorials/first-analysis.md
      - Batch Processing: tutorials/batch-processing.md
      - SIA-CE Integration: tutorials/sia-ce-integration.md
      - Fast chemstation macros scripting: tutorials\chemstation-macros.md
  - API Reference:
      - ChemStation API: api-reference/chemstation.md
      - SIA API: api-reference/sia.md
      - Error Handling: api-reference/error-handling.md
  - Appendix:
      - Hardware Setup: appendix/hardware-setup.md
      - FAQ: appendix/faq.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/sia-ce/

copyright: Copyright &copy; 2024 Richard Maršala